name: Backend CD workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
        - production
        - development
        required: true
        description: the deployment environment type
      deploy-on-instance:
        type: choice
        options:
        - true
        - false
        required: true
        description: enable the Docker image deployment on EC2 instance (it would use the tag value set in `deployment-image-tag`)
      deployment-image-tag:
        type: string
        required: true
        default: 'latest'
        description: the backend Docker image to use for the instance deployment
      publish-docker-image:
          type: choice
          options:
          - true
          - false
          required: true
          description: indicates if the workflow should build and push the Docker image to the container registry

  push:
    branches: [ main ]


jobs:
  define-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-params.outputs.environment }}
      deploy-on-instance: ${{ steps.set-params.outputs.deploy-on-instance }}
      deployment-image-tag: ${{ steps.set-params.outputs.deployment-image-tag }}
      publish-docker-image: ${{ steps.set-params.outputs.publish-docker-image }}
      image-tag: ${{ steps.set-params.outputs.image-tag }}
    steps:
        - uses: actions/checkout@v4
        - name: Set workflow parameters
          working-directory: ./backend
          id: set-params
          run: |
            echo "deployment_environment=${{ inputs.environment || 'development' }}" >> $GITHUB_OUTPUT
            echo "deploy_instance=${{ inputs.deploy-on-instance || true }}" >> $GITHUB_OUTPUT
            echo "backend_image_tag=${{ inputs.deployment-image-tag || 'latest' }}" >> $GITHUB_OUTPUT
            echo "publish_image=${{ inputs.publish-docker-image || true }}" >> $GITHUB_OUTPUT
            echo "image-tag=$(python -c 'import app; print(app.__version__)')" >> $GITHUB_OUTPUT
